name: Dart CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: lesson-087
      PROJECT_ID: flutterflow-lion-poc
      GIT_TAG: $COMMIT_SHA

    steps:
      - uses: actions/checkout@v1

      - uses: google-github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true
        
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: 3.24.3
      - run: flutter pub get
      - run: flutter build web

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: chamindafdo/lion-flutter-app-images
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Push Docker Image to Artifact Registry
        
        run: |-
            docker tag $IMAGE_NAME:latest us-central1-docker.pkg.dev/flutterflow-lion-poc/cicdtest/$PROJECT_ID/images/$IMAGE_NAME:latest
            docker tag $IMAGE_NAME:latest us-central1-docker.pkg.dev/flutterflow-lion-poc/cicdtest/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
            docker push us-central1-docker.pkg.dev/flutterflow-lion-poc/cicdtest/$PROJECT_ID/images/$IMAGE_NAME:latest
            docker push us-central1-docker.pkg.dev/flutterflow-lion-poc/cicdtest/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG    

           
