name: Dart CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: lb-python-app
      PROJECT_ID: flutterflow-lion-poc
      GIT_TAG: testTag

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: 3.24.3
      - run: flutter pub get
      - run: flutter build web
      
      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true


      - name: build and push the docker image
        env:
         GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
         IMAGE_NAME: lb-python-app
         REPO: cicdtest
        run: |
         gcloud auth configure-docker us-central1-docker.pkg.dev
         docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT/$REPO/$IMAGE_NAME:latest .
         docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/$REPO/$IMAGE_NAME:latest

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
          service: 'lb-flutter-app'
          REPO: cicdtest
          image: 'us-central1-docker.pkg.dev/flutterflow-lion-poc/cicdtest/lb-python-app:latest'
          region: 'us-central1'
          port: 80

      #- name: Build & push Docker image
      #  uses: mr-smithers-excellent/docker-build-push@v5
      #   with:
      #    image: chamindafdo/lion-flutter-app-images
      #    tags: latest
      #    registry: docker.io
      #     dockerfile: Dockerfile
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}

      #- name: Build Docker Image
      #  run: docker build -t $IMAGE_NAME:latest .

     # - name: Configure Docker Client
     #    run: |-
     #     gcloud auth configure-docker --quiet
     #     gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
          
   
        
       # run: |-
       #     docker tag $IMAGE_NAME:latest us-central1-docker.pkg.dev/flutterflow-lion-poc/cicdtest/$IMAGE_NAME:latest
       #     # docker push us-central1-docker.pkg.dev/flutterflow-lion-poc/cicdtest/test123:latest
       #    docker push  us-central1-docker.pkg.dev/flutterflow-lion-poc/cicdtest/$IMAGE_NAME:latest


           
