name: Dart CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: lesson-087
      PROJECT_ID: flutterflow-lion-poc

    steps:
      - uses: actions/checkout@v1

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true
        
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: 3.24.3
      - run: flutter pub get
      - run: flutter build web

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: chamindafdo/lion-flutter-app-images
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
